# Generated by Django 4.0.3 on 2022-04-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="type",
            name="pokemon",
        ),
        migrations.AddField(
            model_name="type",
            name="pokemon",
            field=models.ManyToManyField(to="pokemon.pokemon", verbose_name="Pokemon"),
        ),
    ]
