# Generated by Django 4.1.1 on 2022-09-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_remove_type_pokemon_type_pokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
